spring.datasource.url=jdbc:mysql://localhost/TRADER_SLAVE?maxAllowedPacket=134217728
spring.datasource.username=root
spring.datasource.password=
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false